name: addictx
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  image: ^2.1.14
  cached_network_image:
  google_sign_in:
  firebase_auth: ^0.18.0
  firebase_auth_web: ^0.3.2
  cloud_firestore:
  firebase_storage:
  shared_preferences:
  firebase_core:
  fluttertoast:
  image_picker:
  uuid:
  google_fonts: ^1.1.0
  font_awesome_flutter: ^9.0.0
  animations:
  video_compress:
  story_view:
  path_provider:
  image_cropper:
  camera:
  cached_video_player:
  step_progress_indicator: ^1.0.1
  custom_navigation_bar: ^0.8.1
  firebase_messaging:
  percent_indicator:
  visibility_detector: ^0.1.5
  flutter_countdown_timer:
  vibration:
  intro_slider:
  faker:
  permission_handler: ^5.0.1+1
  image_gallery_saver:
  flutter_swiper:
  flutter_animator:
  audioplayer:
  flutter_staggered_grid_view:
  dio: ^3.0.10
  photo_view:
  popup_menu:
  flutter_speed_dial:
  dotted_border: ^2.0.0
  flutter_dialogflow: ^0.1.3
  progress_indicators:
  url_launcher:
  fl_chart: ^0.35.0
  share: ^0.6.4+3
  store_redirect: ^1.0.2
  pimp_my_button: ^1.0.0
  random_color: ^1.0.5
  avatar_glow:
  tflite: ^1.1.1
  hive:
  jiffy:
  pedometer:
    git:
      url: git://github.com/feelfreelinux/flutter-plugins.git
      path: packages/pedometer
  hive_flutter: ^0.3.0+2
  liquid_swipe: ^2.1.0
  smooth_page_indicator: ^0.2.3
  flutter_tts: ^3.0.0
  provider: ^5.0.0
  translator:
  http:
  flutter_inappwebview: ^3.0.0
  flutter_toggle_tab: ^1.1.4
  syncfusion_flutter_gauges:
  google_ml_kit: ^0.6.0
  banner_carousel:
    git: https://github.com/abhishekove/banner_carousel.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/addiction/
    - assets/blueAddiction/
    - assets/intro/
    - assets/rewards/
    - assets/dietList/
    - assets/yogaPoses/
    - assets/relaxingActivities/
    - assets/habitBuilding/
    - assets/audioTherapy/
    - assets/mood/
    - assets/mumblebot-mhrt-720b3aa4ed78.json
    - assets/badges/
    - assets/models/
    - assets/yoga/
    - assets/fonts/
    - help/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Dance
       fonts:
         - asset: assets/fonts/Dance.ttf
     - family: Stair
       fonts:
         - asset: assets/fonts/Stair.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
