Map<String, Map> addictionIntro={
  'Hindi':{
    'socialMedia':'''क्या आप खुद को हर समय सोशल मीडिया पर स्क्रॉल करते हुए पाते हैं? क्या आपको भी लगता है कि यह आपका सारा समय ले रहा है और यह कभी खत्म नहीं हो रहा है? लेकिन मेरे पास समाधान का एक गुच्छा है और हम आपके दिन को उत्पादक बनाने के लिए मिलकर इस पर काम कर सकते हैं।''',
    'fastFood':'''पोषण विशेषज्ञ कहते हैं कि जो भोजन बाहर से स्वादिष्ट लगता है वह वास्तव में अंदर से आपकी प्रतिरोधक क्षमता को धीमा कर सकता है। यदि आप फास्ट फूड को छोड़ कर अपनी प्रतिरक्षा को मजबूत बनाने के इच्छुक हैं, तो मैं आपकी मदद करने के लिए यहां हूं। तो, आइए स्वस्थ भोजन पर स्विच करने पर एक साथ काम करें।''',
    'overeating':'''मेरा मानना है कि आप समझते हैं कि अच्छे आकार में रहने से व्यक्ति को किसी भी चीज़ से अधिक आत्मविश्वास मिलता है और ऐसा तब नहीं हो सकता जब आप पूरे दिन भोजन करते रहें। आपको यह याद रखना होगा कि भोजन ईंधन है चिकित्सा नहीं। आइए मैं आपको उचित आहार के बारे में याद दिलाने और अधिक खाने की आदत को छोड़ने में आपकी मदद करता हूं।''',
    'coffee':'''इसमें कोई शक नहीं कि कॉफी काफी नशीला होता है और आपने यह भी सुना होगा कि किसी भी चीज की अधिकता हानिकारक हो सकती है। बहुत अधिक कैफीन अनिद्रा और चिंता का कारण बन सकता है, तो चलिए आपके लिए ताजा संतरे का रस निचोड़ते हैं और कॉफी पीने की आपकी इच्छा को कम करने के बारे में बात करते हैं।''',
    'procrastination':'''लोग अक्सर विलंब को आलस्य के साथ भ्रमित करते हैं और यदि आप आलसी या विलंब करने वाले नहीं कहलाना चाहते हैं तो चलिए चलते हैं और कार्य करने के लिए आज का दिन पूरा करते हैं। मैं यहां आपकी जांच करने और शेड्यूलिंग के मास्टर बनने के लिए आपका मार्गदर्शन करने के लिए हूं।''',
    'gaming':'''अगर आपको लगता है कि गेमिंग आपकी सभी समस्याओं का समाधान है तो मेरे दोस्त, आप गलत हैं। यह वास्तव में एक गंभीर समस्या है जिस पर ध्यान देने की आवश्यकता है और मैं इसे छोड़ने में आपकी मदद कर सकता हूं। चिंता न करें आइए शुरुआत करते हैं बेबी स्टेप्स से।''',
    'gambling':'''अगर आपको लगता है कि जुआ आपकी सभी समस्याओं का समाधान है तो मेरे दोस्त, आप गलत हैं। यह वास्तव में एक गंभीर समस्या है जिस पर ध्यान देने की आवश्यकता है और मैं इसे छोड़ने में आपकी मदद कर सकता हूं। चिंता न करें आइए शुरुआत करते हैं बेबी स्टेप्स से।''',
    'lying':'''जब भी आप झूठ बोलने वाले हों तो सोचें कि इससे बुरा क्या हो सकता है? यदि आप इसके बारे में सोचते हैं, तो यह ऐसा कुछ नहीं है जिसे छोड़ना बहुत कठिन है। आइए बस सीमाएं निर्धारित करने और फिर उनसे चिपके रहने का अभ्यास करें।''',
    'quarrel':'''खासकर बड़े लोगों के सामने झगड़ना अच्छी आदत नहीं है। इससे आप लोगों के सामने अहंकारी नजर आते हैं। इस स्थिति में आप जो सबसे अच्छा कर सकते हैं, वह है शांत होना और फिर बातचीत करना। आइए यहां शुरू करते हैं।''',
    'notSleeping':'''मैं घड़ी देखता हूं और यह 3 बजे है !!! मुझे समय पर नींद नहीं आती... यह एक ऐसी समस्या है जिसका हम में से कई लोग सामना करते हैं, लेकिन चिंता न करें, मैं आपके दिन को उत्पादक बनाने और खुद को व्यवस्थित करने में आपकी सहायता करूंगा। ताकि आपके पास सोने के लिए पर्याप्त समय हो।''',
    'watchingTv':'''टीवी और सीरीज आपके खाली समय में आनंद लेने के लिए हैं। मुख्य रूप से किशोरों और वयस्कों ने इसकी लत विकसित की। अब हम टेलीविजन और श्रृंखला को मनोरंजन के बजाय अंशकालिक नौकरी के रूप में देखते हैं। यह किसी के स्वास्थ्य और सामाजिक जीवन के लिए हानिकारक है। तो आइए मेरे साथ चलें और उचित आत्म-संयम का अभ्यास करें।''',
    'drugs':'''मैंने तब से ड्रग्स लेना शुरू कर दिया था जब मैं तनाव में था और मुझे तनाव कम करने की जरूरत थी। इस समय आप ऐसा ही सोच रहे हैं। लेकिन क्या आपने कभी इस बात पर विचार किया है कि यह आपके पर्यावरण के साथ-साथ स्वयं को भी कैसे प्रभावित करता है? आइए एक साथ बहुतायत के एक नए साहसिक कार्य की शुरुआत करें।''',
    'alcohol':'''मैंने साथियों के दबाव के कारण, तनाव दूर करने के लिए, आनंद के लिए, और क्योंकि मुझे लगता है कि पीने के बाद मेरा एक नया व्यक्तित्व है, मैंने पीना शुरू कर दिया। ये सबसे आम कारण हैं कि व्यक्ति शराब पीना क्यों शुरू कर देते हैं? हालांकि, यह कभी-कभी लत का कारण बन सकता है। इसलिए शराब बनाने के बजाय, आइए अपने आप को थोड़ा शुद्ध करें और संशोधित करें।''',
    'weed':'''जब से मैं तनाव में थी और मुझे तनाव कम करने की जरूरत थी, मैंने खरपतवार निकालना शुरू कर दिया। इस समय आप ऐसा ही सोच रहे हैं। लेकिन क्या आपने कभी इस बात पर विचार किया है कि यह आपके पर्यावरण के साथ-साथ स्वयं को भी कैसे प्रभावित करता है? आइए एक साथ बहुतायत के एक नए साहसिक कार्य की शुरुआत करें।''',
    'smoking':'''"मैं धूम्रपान करना चाहता हूं क्योंकि मैं तनावग्रस्त हूं," धूम्रपान करने वाला कहता है। इतना ही; धूम्रपान करने का कोई अन्य कारण नहीं है। सही? हालांकि, धूम्रपान आपको कई तरह से मार सकता है। तो, चलो धूम्रपान छोड़ दें, और मैं आपको सिखाऊंगा कि आत्म-नियंत्रण कैसे करें। इसे उनके लिए करें जो आपसे प्यार करते हैं, अपने लिए नहीं।''',
  },
  'English': {
    'socialMedia':'''Do you find yourself scrolling social media all the time? Do you also feel it is consuming all your time and that it is never ending? But I got a bunch of solutions and we can work on it together to make your day productive.''',
    'fastFood':'''Nutritionists say that the food which looks delicious from outside could actually slow down you immune from the inside. If you are willing to make your immune stronger by quitting fast food hang on, I am here to help you out. So, let’s work together on switching to healthier food.''',
    'overeating':'''I believe you understand being in a good shape gives an individual more confidence than anything and that cannot happen if you continue munching on food all day. You have to remember that food is fuel not therapy. Let me help you to remind about proper diet and help you quit the habit of overeating.''',
    'coffee':'''There’s no doubt that coffee is quite addictive and you might as well have heard that excess of anything can be harmful. Too much caffeine can cause insomnia and anxiety so let’s squeeze fresh orange juice for you instead and talk about minimizing your urge to drink coffee.''',
    'procrastination':'''People often confuse Procrastination with laziness and if you don’t want to be called either lazy or a procrastinator then let’s go and complete todays to do task. I am here to check on you and guide you to become a master of scheduling.''',
    'gaming':'''If you think gaming is the solution to all your problems then my friend, you’re wrong. It’s a really serious problem that need attention and I can help you in quitting it. Don’t worry let’s start with baby steps.''',
    'gambling':'''If you think gambling is the solution to all your problems then my friend, you’re wrong. It’s a really serious problem that need attention and I can help you in quitting it. Don’t worry let’s start with baby steps.''',
    'lying':'''Whenever you are about to lie think what’s the worst that can happen? If you think about it, it’s not something that’s very hard to quit. Let’s just start by practicing setting boundaries and then sticking to them.''',
    'quarrel':'''Quarrelling is not a good habit especially in front of senior people. It makes you look arrogant in front of people. The best you can do in this situation is to cool down and then have a conversation. Let’s begin here.''',
    'notSleeping':'''I look at the clock and it's 3 a.m.!!! I can't seem to fall asleep on time... It is an issue that many of us face, but don't worry, I will assist you in making your day productive and organising yourself. so that you have enough time to sleep.''',
    'watchingTv':'''T.V. and series are meant to be enjoyed in your spare time. Primarily teenagers and adults developed an addiction to it. We now watch television and series as a part-time job rather than as a pastime. This is harmful to one's health and social life. So let's come along with me and exercise proper self-control.''',
    'drugs':'''I ended up taking drugs since I was stressed and needed to de-stress. That's how you're thinking right now. But have you ever considered how it impacts your environment, as well as yourself? Let's embark on a new adventure of abundance together.''',
    'alcohol':'''I started drinking because of peer pressure, to relieve stress, for pleasure, and because I feel like I have a new personality after drinking. These are the most frequent reasons why individuals start drinking? However, it can sometimes lead to addiction. So instead of creating booze, let's cleanse and modify ourselves a little.''',
    'weed':'''I ended up taking weeds since I was stressed and needed to de-stress. That's how you're thinking right now. But have you ever considered how it impacts your environment, as well as yourself? Let's embark on a new adventure of abundance together.''',
    'smoking':'''"I want to smoke because I'm stressed," says the smoker. That's it; there's no other reason to smoke. Right? However, smoking can kill you in a variety of ways. So, let's quit smoking, and I'll teach you how to self-control. Do it for those who love you, not for yourself.''',
  },
  'Spanish': {
    'socialMedia':'''¿Te encuentras navegando por las redes sociales todo el tiempo? ¿Sientes también que te consume todo el tiempo y que no se acaba nunca? Pero tengo un montón de soluciones y podemos trabajar juntos para que su día sea productivo.''',
    'fastFood':'''Los nutricionistas dicen que la comida que se ve deliciosa desde el exterior en realidad podría ralentizar su inmunidad desde el interior. Si está dispuesto a fortalecer su sistema inmunológico al dejar la comida rápida, espere, estoy aquí para ayudarlo. Por lo tanto, trabajemos juntos para cambiar a alimentos más saludables.''',
    'overeating':'''Creo que entiendes que estar en buena forma le da a una persona más confianza que cualquier otra cosa y eso no puede suceder si continúas masticando comida todo el día. Tienes que recordar que la comida es combustible, no terapia. Permítame ayudarlo a recordar la dieta adecuada y ayudarlo a dejar el hábito de comer en exceso.''',
    'coffee':'''No hay duda de que el café es bastante adictivo y es posible que haya escuchado que el exceso de cualquier cosa puede ser dañino. Demasiada cafeína puede causar insomnio y ansiedad, así que exprimamos jugo de naranja fresco para usted y hablemos de minimizar la necesidad de tomar café.''',
    'procrastination':'''La gente a menudo confunde la procrastinación con la pereza y si no quieres que te llamen perezoso o procrastinador, entonces vayamos y completemos la tarea de hoy. Estoy aquí para controlarlo y guiarlo para que se convierta en un maestro de la programación.''',
    'gaming':'''Si crees que los juegos son la solución a todos tus problemas, amigo mío, estás equivocado. Es un problema realmente serio que necesita atención y puedo ayudarlo a dejarlo. No se preocupe, comencemos con los pequeños pasos.''',
    'gambling':'''Si crees que el juego es la solución a todos tus problemas, amigo mío, estás equivocado. Es un problema realmente serio que necesita atención y puedo ayudarlo a dejarlo. No se preocupe, comencemos con los pequeños pasos.''',
    'lying':'''Siempre que esté a punto de mentir, piense qué es lo peor que puede pasar. Si lo piensa, no es algo que sea muy difícil de dejar. Comencemos por practicar el establecimiento de límites y luego ceñirnos a ellos.''',
    'quarrel':'''Pelear no es un buen hábito, especialmente frente a personas mayores. Te hace parecer arrogante frente a la gente. Lo mejor que puede hacer en esta situación es calmarse y luego tener una conversación. Comencemos aquí.''',
    'notSleeping':'''Miro el reloj y son las 3 a.m. !!! Parece que no puedo quedarme dormido a tiempo ... Es un problema que muchos de nosotros enfrentamos, pero no se preocupe, lo ayudaré a hacer que su día sea productivo y a organizarse. para que tengas suficiente tiempo para dormir.''',
    'watchingTv':'''La televisión y las series están pensadas para disfrutarlas en su tiempo libre. Principalmente, los adolescentes y los adultos desarrollaron una adicción a ella. Ahora vemos televisión y series como un trabajo a tiempo parcial y no como un pasatiempo. Esto es perjudicial para la salud y la vida social. Así que vayamos conmigo y ejerzamos el autocontrol adecuado.''',
    'drugs':'''Empecé a tomar drogas porque estaba estresado y necesitaba desestresarme. Eso es lo que estás pensando ahora mismo. Pero, ¿alguna vez ha considerado cómo afecta a su medio ambiente, así como a usted mismo? Embárquesemos juntos en una nueva aventura de abundancia.''',
    'alcohol':'''Comencé a beber debido a la presión de mis compañeros, para aliviar el estrés, por placer y porque siento que tengo una nueva personalidad después de beber. ¿Estas son las razones más frecuentes por las que las personas comienzan a beber? Sin embargo, a veces puede provocar adicción. Entonces, en lugar de crear alcohol, limpiemos y modifiquémonos un poco.''',
    'weed':'''Empecé a consumir marihuana porque estaba estresado y necesitaba desestresarme. Eso es lo que estás pensando ahora mismo. Pero, ¿alguna vez ha considerado cómo afecta a su medio ambiente, así como a usted mismo? Embárquesemos juntos en una nueva aventura de abundancia.''',
    'smoking':'''"Quiero fumar porque estoy estresado", dice el fumador. Eso es; no hay otra razón para fumar. ¿Derecha? Sin embargo, fumar puede matarlo de varias maneras. Entonces, dejemos de fumar y le enseñaré cómo autocontrolarse. Hazlo por los que te aman, no por ti mismo.''',
  },
  'German': {
    'socialMedia':'''Scrollen Sie ständig in den sozialen Medien? Haben Sie auch das Gefühl, dass es Ihre ganze Zeit in Anspruch nimmt und nie aufhört? Aber ich habe eine Reihe von Lösungen und wir können gemeinsam daran arbeiten, um Ihren Tag produktiver zu gestalten.''',
    'fastFood':'''Ernährungswissenschaftler sagen, dass das Essen, das von außen lecker aussieht, Ihr Immunsystem von innen schwächen könnte. Wenn Sie bereit sind, Ihr Immunsystem zu stärken, indem Sie auf Fast Food verzichten, bin ich hier, um Ihnen zu helfen. Lassen Sie uns also gemeinsam daran arbeiten, auf gesündere Lebensmittel umzustellen.''',
    'overeating':'''Ich glaube, Sie verstehen, dass eine gute Verfassung einem Menschen mehr Selbstvertrauen gibt als alles andere, und das kann nicht passieren, wenn Sie den ganzen Tag weiter essen. Sie müssen sich daran erinnern, dass Nahrung Treibstoff und keine Therapie ist. Lassen Sie mich Ihnen helfen, an die richtige Ernährung zu erinnern und Ihnen zu helfen, die Gewohnheit des Überessens aufzugeben.''',
    'coffee':'''Es besteht kein Zweifel, dass Kaffee süchtig macht und Sie hätten genauso gut gehört, dass ein Übermaß an allem schädlich sein kann. Zu viel Koffein kann Schlaflosigkeit und Angstzustände verursachen, also lassen Sie uns stattdessen frischen Orangensaft für Sie pressen und darüber sprechen, Ihren Drang, Kaffee zu trinken, zu minimieren.''',
    'procrastination':'''Die Leute verwechseln Prokrastination oft mit Faulheit, und wenn Sie weder faul noch als Aufschieber bezeichnet werden möchten, dann lassen Sie uns die heutige Aufgabe erledigen. Ich bin hier, um Sie zu überprüfen und Sie zu einem Meister der Terminplanung zu führen.''',
    'gaming':'''Wenn Sie denken, dass Gaming die Lösung für all Ihre Probleme ist, dann liegen Sie falsch, mein Freund. Es ist ein wirklich ernstes Problem, das Aufmerksamkeit erfordert und ich kann Ihnen helfen, es zu beenden. Keine Sorge, fangen wir mit Babyschritten an.''',
    'gambling':'''Wenn Sie denken, dass Glücksspiel die Lösung für all Ihre Probleme ist, dann liegen Sie falsch, mein Freund. Es ist ein wirklich ernstes Problem, das Aufmerksamkeit erfordert und ich kann Ihnen helfen, es zu beenden. Keine Sorge, fangen wir mit Babyschritten an.''',
    'lying':'''Wann immer du lügen willst, denk daran, was das Schlimmste ist, was passieren kann Wenn Sie darüber nachdenken, ist es nicht sehr schwer, damit aufzuhören. Beginnen wir einfach damit, Grenzen zu setzen und sie dann einzuhalten.''',
    'quarrel':'''Streiten ist keine gute Angewohnheit, besonders vor älteren Leuten. Es lässt dich vor Leuten arrogant wirken Das Beste, was Sie in dieser Situation tun können, ist, sich abzukühlen und dann ein Gespräch zu führen. Beginnen wir hier.''',
    'notSleeping':'''Ich schaue auf die Uhr und es ist 3 Uhr morgens!!! Ich kann nicht rechtzeitig einschlafen... Es ist ein Problem, mit dem viele von uns konfrontiert sind, aber keine Sorge, ich helfe Ihnen, Ihren Tag produktiv zu gestalten und sich selbst zu organisieren. damit Sie genügend Zeit zum Schlafen haben.''',
    'watchingTv':'''TV und Serien sollen in Ihrer Freizeit genossen werden. Vor allem Jugendliche und Erwachsene entwickelten eine Sucht danach. Heute schauen wir Fernsehen und Serien eher als Nebenjob denn als Zeitvertreib. Dies ist schädlich für die Gesundheit und das soziale Leben. Also lasst uns mitkommen und die richtige Selbstbeherrschung üben.''',
    'drugs':'''Ich habe angefangen, Drogen zu nehmen, da ich gestresst war und Stress abbauen musste. So denkst du gerade. Aber haben Sie jemals darüber nachgedacht, wie sich dies auf Ihre Umgebung und auf Sie selbst auswirkt? Lassen Sie uns gemeinsam ein neues Abenteuer der Fülle starten.''',
    'alcohol':'''Ich begann zu trinken, weil ich unter Gruppenzwang war, um Stress abzubauen, zum Vergnügen und weil ich das Gefühl hatte, nach dem Trinken eine neue Persönlichkeit zu haben. Dies sind die häufigsten Gründe, warum Menschen mit dem Trinken beginnen? Es kann jedoch manchmal zu einer Sucht führen. Anstatt also Alkohol zu produzieren, reinigen und modifizieren wir uns ein wenig.''',
    'weed':'''Ich fing an, Unkraut zu nehmen, da ich gestresst war und Stress abbauen musste. So denkst du gerade. Aber haben Sie jemals darüber nachgedacht, wie sich dies auf Ihre Umgebung und auf Sie selbst auswirkt? Lassen Sie uns gemeinsam ein neues Abenteuer der Fülle starten.''',
    'smoking':'''"Ich möchte rauchen, weil ich gestresst bin", sagt der Raucher. Das ist es; Es gibt keinen anderen Grund zu rauchen. Recht? Rauchen kann Sie jedoch auf verschiedene Weise töten. Hören wir also mit dem Rauchen auf und ich werde dir beibringen, wie man sich selbst beherrscht. Tu es für diejenigen, die dich lieben, nicht für dich selbst.''',
  },
  'French': {
    'socialMedia':'''Vous surprenez-vous à faire défiler les réseaux sociaux tout le temps ? Avez-vous également l'impression que cela vous prend tout votre temps et que cela ne s'arrête jamais ? Mais j'ai un tas de solutions et nous pouvons y travailler ensemble pour rendre votre journée productive.''',
    'fastFood':'''Les nutritionnistes disent que la nourriture qui a l'air délicieuse de l'extérieur pourrait en fait ralentir votre immunité de l'intérieur. Si vous êtes prêt à renforcer votre système immunitaire en abandonnant la restauration rapide, je suis là pour vous aider. Alors, travaillons ensemble pour passer à une alimentation plus saine.''',
    'overeating':'''Je crois que vous comprenez qu'être en bonne forme donne à un individu plus de confiance que tout et cela ne peut pas arriver si vous continuez à grignoter de la nourriture toute la journée. Vous devez vous rappeler que la nourriture est un carburant et non une thérapie. Permettez-moi de vous aider à vous souvenir d'une bonne alimentation et de vous aider à arrêter de trop manger.''',
    'coffee':'''Il ne fait aucun doute que le café est assez addictif et vous pourriez aussi bien avoir entendu dire que l'excès de tout peut être nocif. Trop de caféine peut causer de l'insomnie et de l'anxiété, alors pressons-nous plutôt du jus d'orange frais pour vous et parlons de la réduction de votre envie de boire du café.''',
    'procrastination':'''Les gens confondent souvent la procrastination avec la paresse et si vous ne voulez pas être traité de paresseux ou de procrastinateur, alors allons-y et complétons la tâche d'aujourd'hui. Je suis là pour vous surveiller et vous guider pour devenir un maître de la planification.''',
    'gaming':'''Si vous pensez que le jeu est la solution à tous vos problèmes, alors mon ami, vous vous trompez. C'est un problème vraiment grave qui nécessite une attention et je peux vous aider à le quitter. Ne vous inquiétez pas, commençons par des petits pas.''',
    'gambling':'''Si vous pensez que le jeu est la solution à tous vos problèmes, alors mon ami, vous vous trompez. C'est un problème vraiment grave qui nécessite une attention et je peux vous aider à le quitter. Ne vous inquiétez pas, commençons par des petits pas.''',
    'lying':'''Chaque fois que vous êtes sur le point de mentir, pensez au pire qui puisse arriver ? Si vous y réfléchissez, ce n'est pas quelque chose de très difficile à arrêter. Commençons simplement par nous entraîner à fixer des limites, puis à nous y tenir.''',
    'quarrel':'''Se quereller n'est pas une bonne habitude, surtout devant des personnes âgées. Cela vous fait paraître arrogant devant les gens. Le mieux que vous puissiez faire dans cette situation est de vous calmer puis d'avoir une conversation. Commençons ici.''',
    'notSleeping':'''Je regarde l'heure et il est 3h du matin !!! Je n'arrive pas à m'endormir à temps... C'est un problème auquel beaucoup d'entre nous sont confrontés, mais ne vous inquiétez pas, je vais vous aider à rendre votre journée productive et à vous organiser. afin que vous ayez suffisamment de temps pour dormir.''',
    'watchingTv':'''La télévision et les séries sont faites pour être appréciées pendant votre temps libre. Ce sont principalement les adolescents et les adultes qui y ont développé une dépendance. Nous regardons désormais la télévision et les séries comme un travail à temps partiel plutôt que comme un passe-temps. Cela nuit à la santé et à la vie sociale. Alors venez avec moi et exerçons une bonne maîtrise de soi.''',
    'drugs':'''J'ai commencé à me droguer car j'étais stressé et j'avais besoin de déstresser. C'est comme ça que tu penses en ce moment. Mais avez-vous déjà réfléchi à son impact sur votre environnement, ainsi que sur vous-même ? Embarquons ensemble dans une nouvelle aventure d'abondance.''',
    'alcohol':'''J'ai commencé à boire à cause de la pression des pairs, pour soulager le stress, pour le plaisir et parce que j'ai l'impression d'avoir une nouvelle personnalité après avoir bu. Ce sont les raisons les plus fréquentes pour lesquelles les individus commencent à boire ? Cependant, cela peut parfois conduire à une dépendance. Alors au lieu de créer de l'alcool, nettoyons-nous et modifions-nous un peu.''',
    'weed':'''J'ai commencé à prendre des mauvaises herbes car j'étais stressé et j'avais besoin de déstresser. C'est comme ça que tu penses en ce moment. Mais avez-vous déjà réfléchi à son impact sur votre environnement, ainsi que sur vous-même ? Embarquons ensemble dans une nouvelle aventure d'abondance.''',
    'smoking':'''"Je veux fumer parce que je suis stressé", dit le fumeur. C'est ça; il n'y a aucune autre raison de fumer. Droite? Cependant, fumer peut vous tuer de diverses manières. Alors, arrêtons de fumer, et je vais t'apprendre à te contrôler. Faites-le pour ceux qui vous aiment, pas pour vous-même.''',
  },
  'Japanese': {
    'socialMedia':'''あなたはいつもソーシャルメディアをスクロールしていると思いますか？また、それはあなたのすべての時間を消費していて、それが決して終わらないと感じますか？しかし、私はたくさんの解決策を手に入れました、そして私たちはあなたの一日を生産的にするために一緒に取り組むことができます。''',
    'fastFood':'''栄養士は、外から見て美味しそうな食べ物は、実際には内からの免疫を遅くする可能性があると言います。あなたがファーストフードをやめることによってあなたの免疫力をより強くすることをいとわないなら、私はあなたを助けるためにここにいます。それでは、より健康的な食品への切り替えに協力しましょう。''',
    'overeating':'''体調が良いことは、何よりも個人に自信を与えることを理解していると思います。一日中食べ物を食べ続けると、それは起こり得ません。食べ物は治療ではなく燃料であることを覚えておく必要があります。適切な食事を思い出させ、過食の習慣をやめるのを手伝いましょう。''',
    'coffee':'''コーヒーはかなり中毒性があることは間違いありません。過剰なものは有害である可能性があると聞いたことがあるかもしれません。カフェインが多すぎると不眠症や不安神経症を引き起こす可能性があるので、代わりに新鮮なオレンジジュースを絞り、コーヒーを飲みたいという衝動を最小限に抑えることについて話しましょう。''',
    'procrastination':'''人々はしばしば先延ばしを怠惰と混同します。怠惰または先延ばしと呼ばれたくない場合は、今日行ってタスクを完了しましょう。私はあなたをチェックし、スケジューリングのマスターになるためにあなたを導くためにここにいます。''',
    'gaming':'''ゲームがあなたのすべての問題の解決策だと思うなら、私の友人、あなたは間違っています。これは本当に深刻な問題であり、注意が必要です。私はあなたがそれをやめるのを手伝うことができます。心配しないで、赤ちゃんのステップから始めましょう。''',
    'gambling':'''ギャンブルがあなたのすべての問題の解決策だと思うなら、私の友人、あなたは間違っています。これは本当に深刻な問題であり、注意が必要です。私はあなたがそれをやめるのを手伝うことができます。心配しないで、赤ちゃんのステップから始めましょう。''',
    'lying':'''嘘をつくときはいつでも、起こりうる最悪の事態は何だと思いますか？考えてみれば、やめるのはそれほど難しいことではありません。境界を設定する練習をしてから、それに固執することから始めましょう。''',
    'quarrel':'''特に高齢者の前では、喧嘩は良い習慣ではありません。それはあなたを人々の前で傲慢に見せます。この状況でできる最善のことは、クールダウンしてから会話することです。ここから始めましょう。''',
    'notSleeping':'''時計を見ると午前3時です!!!時間通りに眠れないようです...私たちの多くが直面している問題ですが、心配しないでください。私はあなたの一日を生産的にし、自分自身を整理するのを手伝います。寝るのに十分な時間があるように。''',
    'watchingTv':'''T.V.とシリーズはあなたの暇な時間に楽しむことを意図しています。主にティーンエイジャーと大人はそれに中毒を開発しました。私たちは今、テレビやシリーズを娯楽としてではなくアルバイトとして見ています。これは人の健康と社会生活に有害です。だから私と一緒に来て、適切な自制心を働かせましょう。''',
    'drugs':'''ストレスを感じ、ストレスを解消する必要があったので、薬を飲み始めました。それがあなたが今考えている方法です。しかし、それがあなた自身だけでなくあなたの環境にどのように影響するかを考えたことがありますか？一緒に豊かさの新しい冒険に乗り出しましょう。''',
    'alcohol':'''仲間からのプレッシャー、ストレス解消、快楽、そして飲んだ後の新しい性格を感じて飲み始めました。これらは、個人が飲み始める最も頻繁な理由ですか？しかし、それは時々中毒につながる可能性があります。だから、酒を作る代わりに、自分自身を少し浄化して修正しましょう。''',
    'weed':'''ストレスを感じてストレスを解消する必要があったので、雑草を取り始めました。それがあなたが今考えている方法です。しかし、それがあなた自身だけでなくあなたの環境にどのように影響するかを考えたことがありますか？一緒に豊かさの新しい冒険に乗り出しましょう。''',
    'smoking':'''「ストレスがたまっているので喫煙したい」と喫煙者は言う。それでおしまい;喫煙する理由は他にありません。正しい？しかし、喫煙はさまざまな方法であなたを殺すことができます。それでは、喫煙をやめましょう。自己管理の方法をお教えします。あなた自身のためではなく、あなたを愛する人々のためにそれをしてください。''',
  },
  'Russian': {
    'socialMedia':'''Вы постоянно просматриваете социальные сети? Вы также чувствуете, что это отнимает все ваше время и никогда не кончается? Но у меня есть несколько решений, и мы можем работать над ними вместе, чтобы сделать ваш день продуктивным.''',
    'fastFood':'''Диетологи говорят, что еда, которая выглядит восхитительно снаружи, может снизить иммунитет изнутри. Если вы хотите укрепить свой иммунитет, отказавшись от фастфуда, я здесь, чтобы помочь вам. Итак, давайте вместе поработаем над переходом на более здоровую пищу.''',
    'overeating':'''Я считаю, вы понимаете, что хорошая форма дает человеку больше уверенности, чем что-либо другое, и этого не может произойти, если вы продолжаете жевать еду весь день. Вы должны помнить, что еда - это топливо, а не терапия. Позвольте мне помочь вам напомнить о правильном питании и помочь вам избавиться от привычки переедать.''',
    'coffee':'''Нет никаких сомнений в том, что кофе вызывает привыкание, и вы также могли слышать, что избыток чего-либо может быть вредным. Слишком много кофеина может вызвать бессонницу и беспокойство, поэтому давайте вместо этого выжимаем для вас свежий апельсиновый сок и поговорим о том, как уменьшить ваше желание пить кофе.''',
    'procrastination':'''Люди часто путают прокрастинацию с ленью, и если вы не хотите, чтобы вас называли ленивцем или прокрастинатором, тогда давайте и сделаем сегодняшнее задание. Я здесь, чтобы проверить вас и помочь вам стать мастером планирования.''',
    'gaming':'''Если вы думаете, что игры - это решение всех ваших проблем, тогда, друг мой, вы ошибаетесь. Это действительно серьезная проблема, требующая внимания, и я могу помочь вам с ней справиться. Не волнуйтесь, давайте начнем с маленьких шагов.''',
    'gambling':'''Если вы думаете, что азартные игры - это решение всех ваших проблем, тогда, друг мой, вы ошибаетесь. Это действительно серьезная проблема, требующая внимания, и я могу помочь вам с ней справиться. Не волнуйтесь, давайте начнем с маленьких шагов.''',
    'lying':'''Каждый раз, когда вы собираетесь солгать, подумайте, что самое худшее, что может случиться? Если задуматься, бросить это не так уж и сложно. Давайте начнем с практики, устанавливая границы, а затем придерживаясь их.''',
    'quarrel':'''Ссоры - плохая привычка, особенно в присутствии пожилых людей. Это заставляет вас выглядеть высокомерно перед людьми. Лучшее, что вы можете сделать в этой ситуации, - это остыть, а затем поговорить. Начнем здесь.''',
    'notSleeping':'''Я смотрю на часы, а сейчас 3 часа ночи !!! Кажется, я не могу заснуть вовремя ... Это проблема, с которой сталкиваются многие из нас, но не волнуйтесь, я помогу вам сделать ваш день продуктивным и организовать себя. чтобы у вас было достаточно времени, чтобы выспаться.''',
    'watchingTv':'''Телевидение и сериалы предназначены для просмотра в свободное время. В первую очередь к нему пристрастились подростки и взрослые. Теперь мы смотрим телевизор и сериалы как подработку, а не как времяпрепровождение. Это вредно для здоровья и общественной жизни. Так что давайте пойдем со мной и проявим надлежащий самоконтроль.''',
    'drugs':'''Я начал принимать наркотики, так как был в состоянии стресса и мне нужно было снять стресс. Вот как вы сейчас думаете. Но задумывались ли вы когда-нибудь о том, как это влияет на вашу окружающую среду, а также на вас самих? Давайте вместе отправимся в новое приключение изобилия.''',
    'alcohol':'''Я начал пить из-за давления со стороны сверстников, для снятия стресса, для удовольствия и потому, что после выпивки я чувствую, что у меня изменилась личность. Это самые частые причины, по которым люди начинают пить? Однако иногда это может привести к зависимости. Так что вместо того, чтобы создавать выпивку, давайте немного очистимся и изменим себя.''',
    'weed':'''Я начал употреблять сорняки, так как был в стрессе и нуждался в снятии стресса. Вот как вы сейчас думаете. Но задумывались ли вы когда-нибудь о том, как это влияет на вашу окружающую среду, а также на вас самих? Давайте вместе отправимся в новое приключение изобилия.''',
    'smoking':'''«Я хочу курить, потому что у меня стресс», - говорит курильщик. Это оно; нет другой причины курить. Верно? Однако курение может убить вас разными способами. Итак, бросим курить, и я научу вас контролировать себя. Делайте это для тех, кто любит вас, а не для себя.''',
  },
  'Chinese': {
    'socialMedia':'''您是否发现自己一直在滚动社交媒体？你是否也觉得它正在消耗你所有的时间并且它永无止境？但是我得到了很多解决方案，我们可以共同努力，让您的一天富有成效。''',
    'fastFood':'''营养学家说，从外面看起来很美味的食物实际上会减慢你对内部的免疫力。如果你愿意通过戒掉快餐来增强你的免疫力，我会在这里帮助你。所以，让我们共同努力转向更健康的食物。''',
    'overeating':'''我相信您明白，良好的体型比任何事情都更能让人充满信心，如果您整天大嚼食物，这种情况就不会发生。你必须记住，食物是燃料而不是治疗。让我来帮助您提醒适当的饮食，并帮助您戒掉暴饮暴食的习惯。''',
    'coffee':'''毫无疑问，咖啡很容易让人上瘾，你也可能听说过任何过量的东西都是有害的。过多的咖啡因会导致失眠和焦虑，所以让我们为你榨出新鲜的橙汁，并谈谈尽量减少喝咖啡的冲动。''',
    'procrastination':'''人们经常将拖延症与懒惰混淆，如果你不想被称为懒惰者或拖延者，那么让我们去完成今天的任务吧。我是来看你的，指导你成为调度高手。''',
    'gaming':'''如果你认为游戏可以解决你所有的问题，那么我的朋友，你错了。这是一个非常严重的问题，需要引起注意，我可以帮助您戒烟。别担心，让我们从婴儿的步骤开始。''',
    'gambling':'''如果你认为赌博可以解决你所有的问题，那么我的朋友，你错了。这是一个非常严重的问题，需要引起注意，我可以帮助您戒烟。别担心，让我们从婴儿的步骤开始。''',
    'lying':'''每当你要撒谎时，想想可能发生的最坏情况是什么？仔细想想，这并不是一件很难戒掉的事情。让我们先练习设定界限，然后坚持下去。''',
    'quarrel':'''吵架不是一个好习惯，尤其是在长辈面前。这会让你在人前显得傲慢。在这种情况下，您能做的最好的事情就是冷静下来，然后进行交谈。让我们从这里开始。''',
    'notSleeping':'''我一看表，已经是凌晨三点了！！！我似乎无法按时入睡……这是我们许多人都面临的问题，但别担心，我会帮助您使您的一天富有成效并组织好自己。这样你就有足够的时间睡觉。''',
    'watchingTv':'''电视和连续剧旨在让您在业余时间欣赏。主要是青少年和成年人对它上瘾。我们现在看电视和连续剧是一种兼职工作，而不是一种消遣。这对一个人的健康和社交生活是有害的。所以，让我们和我一起来，锻炼适当的自我控制。''',
    'drugs':'''自从我感到压力和需要减压以来，我就开始吸毒。这就是你现在的想法。但是您有没有考虑过它如何影响您的环境以及您自己？让我们一起踏上丰盛的新冒险。''',
    'alcohol':'''我开始喝酒是因为同伴的压力，是为了缓解压力，是为了快乐，也是因为我觉得喝酒后我有了新的个性。这些是人们开始饮酒的最常见原因？然而，它有时会导致上瘾。因此，与其制造豪饮，不如让我们稍微清洁和调整一下自己。''',
    'weed':'''自从我感到压力并需要减压以来，我就开始服用杂草。这就是你现在的想法。但是您有没有考虑过它如何影响您的环境以及您自己？让我们一起踏上丰盛的新冒险。''',
    'smoking':'''“我想吸烟是因为我有压力，”吸烟者说。就是这样;没有其他理由吸烟。正确的？但是，吸烟可以通过多种方式杀死您。所以，让我们戒烟吧，我来教你如何自控。为爱你的人做这件事，而不是为你自己。''',
  },
  'Portuguese': {
    'socialMedia':'''Você se pega navegando nas redes sociais o tempo todo? Você também sente que está consumindo todo o seu tempo e que nunca acaba? Mas eu tenho um monte de soluções e podemos trabalhar nisso juntos para tornar o seu dia produtivo.''',
    'fastFood':'''Os nutricionistas dizem que a comida que parece deliciosa por fora pode, na verdade, retardar sua imunidade por dentro. Se você está disposto a fortalecer seu sistema imunológico abandonando o fast food, espere, estou aqui para ajudá-lo. Então, vamos trabalhar juntos para mudar para uma alimentação mais saudável.''',
    'overeating':'''Acredito que você entenda que estar em boa forma dá ao indivíduo mais confiança do que qualquer outra coisa e isso não pode acontecer se você continuar mastigando comida o dia todo. Você tem que lembrar que comida é combustível e não terapia. Deixe-me ajudá-lo a lembrar sobre uma dieta adequada e ajudá-lo a abandonar o hábito de comer demais.''',
    'coffee':'''Não há dúvida de que o café é bastante viciante e você também pode ter ouvido que o excesso de qualquer coisa pode ser prejudicial. Muita cafeína pode causar insônia e ansiedade, então vamos espremer suco de laranja fresco para você e falar sobre como minimizar sua vontade de beber café.''',
    'procrastination':'''As pessoas costumam confundir procrastinação com preguiça e se você não quer ser chamado de preguiçoso ou procrastinador, vamos terminar o dia de hoje para fazer a tarefa. Estou aqui para verificar como você está e orientá-lo para que se torne um mestre em programação.''',
    'gaming':'''Se você acha que jogar é a solução para todos os seus problemas, meu amigo, você está errado. É um problema muito sério que precisa de atenção e posso ajudá-lo a abandoná-lo. Não se preocupe, vamos começar com pequenos passos.''',
    'gambling':'''Se você acha que o jogo é a solução para todos os seus problemas, meu amigo, você está errado. É um problema muito sério que precisa de atenção e posso ajudá-lo a abandoná-lo. Não se preocupe, vamos começar com pequenos passos.''',
    'lying':'''Sempre que você estiver prestes a mentir, pense qual é a pior coisa que pode acontecer? Se você pensar bem, não é algo muito difícil de parar. Vamos apenas começar praticando o estabelecimento de limites e, em seguida, aderindo a eles.''',
    'quarrel':'''Brigar não é um bom hábito, especialmente na frente de pessoas mais velhas. Faz você parecer arrogante na frente das pessoas. O melhor que você pode fazer nessa situação é se acalmar e depois conversar. Vamos começar aqui.''',
    'notSleeping':'''Eu olho para o relógio e são 3 da manhã !!! Não consigo dormir a tempo ... É um problema que muitos de nós enfrentamos, mas não se preocupe, vou ajudá-lo a tornar o seu dia produtivo e a se organizar. para que você tenha tempo suficiente para dormir.''',
    'watchingTv':'''A TV e as séries foram concebidas para serem desfrutadas no seu tempo livre. Principalmente adolescentes e adultos desenvolveram um vício nisso. Agora assistimos à televisão e às séries como um trabalho de meio período, e não como um passatempo. Isso é prejudicial à saúde e à vida social. Portanto, vamos comigo e exercer o autocontrole adequado.''',
    'drugs':'''Comecei a usar drogas porque estava estressado e precisava desestressar. É assim que você está pensando agora. Mas você já considerou como isso afeta seu meio ambiente, assim como você mesmo? Vamos embarcar juntos em uma nova aventura de abundância.''',
    'alcohol':'''Comecei a beber por causa da pressão dos colegas, para aliviar o estresse, por prazer e porque sinto que tenho uma nova personalidade depois de beber. Estas são as razões mais frequentes pelas quais as pessoas começam a beber? No entanto, às vezes pode levar ao vício. Portanto, em vez de criar bebidas alcoólicas, vamos nos limpar e modificar um pouco.''',
    'weed':'''Comecei a tirar ervas daninhas porque estava estressado e precisava desestressar. É assim que você está pensando agora. Mas você já considerou como isso afeta seu meio ambiente, assim como você mesmo? Vamos embarcar juntos em uma nova aventura de abundância.''',
    'smoking':'''“Quero fumar porque estou estressado”, diz o fumante. É isso; não há outra razão para fumar. Direito? No entanto, fumar pode matar você de várias maneiras. Então, vamos parar de fumar, e eu vou te ensinar como ter autocontrole. Faça isso por aqueles que o amam, não por você mesmo.''',
  },
};

Map<String, Map> activityDetails={
  'Hindi':{
    'Breathing':'कुछ देर के लिए अपनी सांसों को सुंदर फेफड़ों में बदलें।',
    'Walking':'एक रास्ता चुनें और तब तक चलें जब तक फिटनेस की मंजिल हासिल न हो जाए।',
    'Jogging':'दौड़ते समय बस याद रखें कि आप अपने अनुपयुक्त शरीर से भाग रहे हैं।',
    'Swimming':'पूरी तरह से आकार का शरीर और मन प्राप्त करने के लिए उन धाराओं का मुकाबला करें।',
    'Cycling':'शरीर को मजबूत करने के लिए, अपनी पूरी क्षमता के साथ चक्र को गति दें।',
    'Stair Climbing':'बुनियादी सीढ़ियां चढ़कर फिटनेस की सीढ़ी चढ़ें।',
    'Dancing':'नृत्य एड़ी के स्वास्थ्य को अंदर और बाहर दोनों से मदद करता है।',
    'Yoga':'योग आपके शरीर के उन विभिन्न क्षेत्रों को टैप करने में आपकी मदद करेगा जिन्हें आप कभी नहीं जानते थे।',
  },
  'English':{
    'Breathing':'Modify your breaths for a while to the beautiful lungs.',
    'Walking':'Choose a path and walk until destination of fitness is achieved.',
    'Jogging':'While running just remember you are running from your unfit body.',
    'Swimming':'Counter those currents to attain perfectly shaped body and mind.',
    'Cycling':'To strengthen the body, peddle the cycle with all of your potential.',
    'Stair Climbing':'Climb the ladder of fitness by climbing the basic staircase.',
    'Dancing':'Dance helps heal health both from inside and outside.',
    'Yoga':'Yoga will help you tap different areas of your body you never knew.',
  },
  'Spanish':{
    'Breathing':'Modifique su respiración por un tiempo a los hermosos pulmones.',
    'Walking':'Elija un camino y camine hasta lograr el destino de fitness.',
    'Jogging':'Mientras corres, recuerda que estás huyendo de tu cuerpo no apto.',
    'Swimming':'Contrarresta esas corrientes para lograr un cuerpo y una mente perfectamente formados.',
    'Cycling':'Para fortalecer el cuerpo, transmita el ciclo con todo su potencial.',
    'Stair Climbing':'Sube la escalera del fitness subiendo la escalera básica.',
    'Dancing':'La danza ayuda a sanar la salud tanto desde dentro como desde fuera.',
    'Yoga':'El yoga te ayudará a aprovechar diferentes áreas de tu cuerpo que nunca conociste.',
  },
  'German':{
    'Breathing':'Ändern Sie Ihre Atemzüge für eine Weile zu den schönen Lungen.',
    'Walking':'Wählen Sie einen Weg und gehen Sie, bis das Ziel der Fitness erreicht ist.',
    'Jogging':'Denken Sie beim Laufen daran, dass Sie von Ihrem unfitten Körper weglaufen.',
    'Swimming':'Bekämpfen Sie diese Strömungen, um einen perfekt geformten Körper und Geist zu erreichen.',
    'Cycling':'Um den Körper zu stärken, gehst du mit deinem ganzen Potenzial in den Kreislauf.',
    'Stair Climbing':'Erklimmen Sie die Fitnessleiter, indem Sie die Grundtreppe erklimmen.',
    'Dancing':'Tanz hilft, die Gesundheit von innen und außen zu heilen.',
    'Yoga':'Yoga wird Ihnen helfen, verschiedene Bereiche Ihres Körpers zu erschließen, die Sie noch nie kannten.',
  },
  'French':{
    'Breathing':'Modifiez vos respirations pendant un certain temps pour les beaux poumons.',
    'Walking':"Choisissez un chemin et marchez jusqu'à ce que la destination de remise en forme soit atteinte.",
    'Jogging':"Pendant que vous courez, n'oubliez pas que vous fuyez votre corps inapte.",
    'Swimming':"Contrez ces courants pour atteindre un corps et un esprit parfaitement formés.",
    'Cycling':"Pour renforcer le corps, colportez le cycle avec tout votre potentiel.",
    'Stair Climbing':"Montez les échelons de la condition physique en montant l'escalier de base.",
    'Dancing':"La danse aide à guérir la santé à la fois de l'intérieur et de l'extérieur.",
    'Yoga':"Le yoga vous aidera à exploiter différentes zones de votre corps que vous ne connaissiez pas.",
  },
  'Japanese':{
    'Breathing':'しばらくの間、美しい肺に向かって呼吸を変えてください。',
    'Walking':'パスを選択し、フィットネスの目的地に到達するまで歩きます。',
    'Jogging':'走っている間は、体に合わない体から走っていることを忘れないでください。',
    'Swimming':'それらの流れに対抗して、完璧な形の体と心を実現します。',
    'Cycling':'体を強化するために、あなたのすべての可能性でサイクルを漕いでください。',
    'Stair Climbing':'基本的な階段を上って、フィットネスのはしごを登ります。',
    'Dancing':'ダンスは、内側と外側の両方から健康を癒すのに役立ちます。',
    'Yoga':'ヨガは、あなたが知らなかったあなたの体のさまざまな領域をタップするのに役立ちます。',
  },
  'Russian':{
    'Breathing':'Измените на время свое дыхание на красивые легкие.',
    'Walking':'Выберите путь и идите, пока не достигнете желаемого результата.',
    'Jogging':'Во время бега просто помните, что вы бежите из своего непригодного тела.',
    'Swimming':'Противодействуйте этим течениям, чтобы достичь идеальной формы тела и ума.',
    'Cycling':'Чтобы укрепить тело, используйте весь свой потенциал в цикле.',
    'Stair Climbing':'Поднимитесь по лестнице фитнеса, поднявшись по основной лестнице.',
    'Dancing':'Танец исцеляет здоровье как изнутри, так и снаружи.',
    'Yoga':'Йога поможет вам задействовать различные области вашего тела, о которых вы никогда не знали.',
  },
  'Chinese':{
    'Breathing':'暂时调整呼吸，美肺。',
    'Walking':'选择一条路径并步行，直到达到健身目标。',
    'Jogging':'跑步时请记住，您是在从不健康的身体中跑步。',
    'Swimming':'对抗这些潮流以获得完美的身心。',
    'Cycling':'为了加强身体，用你所有的潜力兜售周期。',
    'Stair Climbing':'通过攀登基本楼梯，攀登健身阶梯。',
    'Dancing':'舞蹈有助于从内到外治愈健康。',
    'Yoga':'瑜伽将帮助您挖掘您从未了解过的身体不同部位。',
  },
  'Portuguese':{
    'Breathing':'Modifique sua respiração por um tempo para os lindos pulmões.',
    'Walking':'Escolha um caminho e caminhe até que o destino do preparo físico seja alcançado.',
    'Jogging':'Enquanto corre, lembre-se de que você está fugindo de seu corpo inapto.',
    'Swimming':'Combata essas correntes para atingir um corpo e uma mente perfeitamente moldados.',
    'Cycling':'Para fortalecer o corpo, faça a bicicleta com todo o seu potencial.',
    'Stair Climbing':'Suba a escada do condicionamento físico subindo a escada básica.',
    'Dancing':'A dança ajuda a curar a saúde tanto interna quanto externamente.',
    'Yoga':'A ioga o ajudará a tocar em diferentes áreas do corpo que você nunca conheceu.',
  },
};

Map<String, Map> habitDetails={
  'Hindi':{
    '0':'व्यर्थ की बातों में समय बर्बाद करने की बजाय सुबह की सैर पर जाने का लक्ष्य है।',
    '1':"जब आप थके हुए हों या समय बर्बाद करने की भावना हो, तो ऑडियो थेरेपी सुनें।",
    '2':"किसी नए शौक या पुराने शौक को कुछ समय दें जो आपने काफी समय से नहीं किया है।",
    '3':"कुछ ऐसा पढ़ें जो आपको चिंतित करता हो, चाहे वह किताब हो, अखबार हो, ब्लॉग हो या पोस्ट का संग्रह हो। अगर आप पाठक नहीं हैं तो इसे आज़माएं।",
    '4':'अपनों के साथ समय बिताएं।',
    '5':'अपने जीवन के लक्ष्यों पर विचार करें और जहां आप सफल होना चाहते हैं, और उन पर काम करना शुरू करें।',
    '6':'अपनी भलाई में निवेश करें। आराम करने और आराम करने के लिए समय निकालने से आपका मूड, मानसिक स्वास्थ्य और आत्म-सम्मान बेहतर होगा। हर दिन कम से कम एक ऐसा काम करें जिससे आपको खुशी मिले।',
  },
  'English':{
    '0':'Instead of wasting time on pointless stuff, the aim is to go for a morning walk.',
    '1':"When you're tired or have feelings of wasting time, listen to the Audio Therapy.",
    '2':"Give some time to a new hobby or an old hobby that you haven't done in a while.",
    '3':"Read something that concerns you, whether it's a book, a newspaper, a blog, or a collection of posts. Give it a shot if you're not a reader.",
    '4':'Spend time with your loved ones.',
    '5':'Consider your life goals and where you want to succeed, and start to work on them.',
    '6':'Invest in your own well-being. Taking time to relax and unwind will improve your mood, mental health, and self-esteem. Every day, do at least one thing that makes you happy.',
  },
  'Spanish':{
    '0':'En lugar de perder el tiempo en cosas inútiles, el objetivo es salir a caminar por la mañana.',
    '1':"Cuando esté cansado o tenga la sensación de perder el tiempo, escuche la Audioterapia.",
    '2':"Dedique algo de tiempo a un nuevo pasatiempo o un pasatiempo antiguo que no haya hecho en un tiempo.",
    '3':"Lea algo que le preocupe, ya sea un libro, un periódico, un blog o una colección de publicaciones. Pruébalo si no eres un lector.",
    '4':'Pase tiempo con sus seres queridos.',
    '5':'Considere las metas de su vida y dónde quiere tener éxito, y comience a trabajar en ellas.',
    '6':'Invierte en tu propio bienestar. Tomarse el tiempo para relajarse y descansar mejorará su estado de ánimo, su salud mental y su autoestima. Todos los días, haz al menos una cosa que te haga feliz.',
  },
  'German':{
    '0':'Anstatt Zeit mit sinnlosen Dingen zu verschwenden, geht es darum, einen Morgenspaziergang zu machen.',
    '1':"Wenn Sie müde sind oder das Gefühl haben, Zeit zu verschwenden, hören Sie sich die Audiotherapie an.",
    '2':"Schenken Sie einem neuen Hobby oder einem alten Hobby, das Sie schon lange nicht mehr gemacht haben, etwas Zeit.",
    '3':"Lesen Sie etwas, das Sie beschäftigt, sei es ein Buch, eine Zeitung, ein Blog oder eine Sammlung von Beiträgen. Probieren Sie es aus, wenn Sie kein Leser sind.",
    '4':'Verbringen Sie Zeit mit Ihren Lieben.',
    '5':'Überlegen Sie sich Ihre Lebensziele und wo Sie erfolgreich sein möchten, und beginnen Sie, daran zu arbeiten.',
    '6':'Investieren Sie in Ihr eigenes Wohlbefinden. Nehmen Sie sich Zeit zum Entspannen und Erholen, um Ihre Stimmung, Ihre geistige Gesundheit und Ihr Selbstwertgefühl zu verbessern. Tue jeden Tag mindestens eine Sache, die dich glücklich macht.',
  },
  'French':{
    '0':'Au lieu de perdre du temps sur des trucs inutiles, le but est de faire une promenade matinale.',
    '1':"Lorsque vous êtes fatigué ou que vous avez l'impression de perdre du temps, écoutez l'audiothérapie.",
    '2':"Donnez du temps à un nouveau passe-temps ou à un ancien passe-temps que vous n'avez pas fait depuis un moment.",
    '3':"Lisez quelque chose qui vous concerne, que ce soit un livre, un journal, un blog ou une collection d'articles. Essayez-le si vous n'êtes pas un lecteur.",
    '4':'Passez du temps avec vos proches.',
    '5':'Considérez vos objectifs de vie et où vous voulez réussir, et commencez à y travailler.',
    '6':'Investissez dans votre propre bien-être. Prendre le temps de se détendre améliorera votre humeur, votre santé mentale et votre estime de soi. Chaque jour, faites au moins une chose qui vous rend heureux.',
  },
  'Japanese':{
    '0':'無意味なものに時間を無駄にする代わりに、目的は朝の散歩に行くことです。',
    '1':"疲れているときや時間を無駄にしているときは、オーディオセラピーを聞いてください。",
    '2':"しばらくしていない新しい趣味や古い趣味に少し時間を割いてください。",
    '3':"それが本、新聞、ブログ、または投稿のコレクションであるかどうかにかかわらず、あなたに関係する何かを読んでください。あなたが読者でないなら、それを試してみてください。",
    '4':'あなたの愛する人と時間を過ごします。',
    '5':'あなたの人生の目標とあなたが成功したい場所を考えて、それらに取り組み始めてください。',
    '6':'あなた自身の幸福に投資してください。リラックスしてくつろぐ時間をとることで、気分、メンタルヘルス、自尊心が向上します。毎日、あなたを幸せにする少なくとも1つのことをしてください。',
  },
  'Russian':{
    '0':'Вместо того, чтобы тратить время на бессмысленные вещи, цель - отправиться на утреннюю прогулку.',
    '1':"Если вы устали или чувствуете, что теряете время зря, послушайте аудиотерапию.",
    '2':"Уделите время новому хобби или старому хобби, которым вы давно не занимались.",
    '3':"Прочтите что-нибудь, что вас беспокоит, будь то книга, газета, блог или сборник сообщений. Попробуйте, если вы не читатель.",
    '4':'Проводите время со своими близкими.',
    '5':'Подумайте о своих жизненных целях и о том, где вы хотите добиться успеха, и начните работать над ними.',
    '6':'Инвестируйте в собственное благополучие. Если вы потратите время на то, чтобы расслабиться и расслабиться, это улучшит ваше настроение, психическое здоровье и самооценку. Каждый день делайте хотя бы одно дело, которое делает вас счастливым.',
  },
  'Chinese':{
    '0':'与其在无意义的事情上浪费时间，不如去晨跑。',
    '1':"当您感到疲倦或有浪费时间的感觉时，请听听音频疗法。",
    '2':"给一个新的爱好或一个你有一段时间没有做过的旧爱好花一些时间。",
    '3':"阅读与您有关的内容，无论是书籍、报纸、博客还是帖子集。如果您不是读者，请试一试。",
    '4':'与您所爱的人共度时光。',
    '5':'考虑你的人生目标和你想成功的地方，然后开始努力。',
    '6':'投资于自己的幸福。花时间放松和放松会改善您的情绪、心理健康和自尊。每天至少做一件让你开心的事。',
  },
  'Portuguese':{
    '0':'Em vez de perder tempo com coisas inúteis, o objetivo é dar um passeio matinal.',
    '1':"Quando estiver cansado ou com sensação de perder tempo, ouça a Audio Terapia.",
    '2':"Dedique algum tempo a um novo hobby ou a um antigo hobby que você não pratica há algum tempo.",
    '3':"Leia algo que o preocupe, seja um livro, um jornal, um blog ou uma coleção de postagens. Experimente, se você não for um leitor.",
    '4':'Passe algum tempo com seus entes queridos.',
    '5':'Considere seus objetivos de vida e onde você deseja ter sucesso e comece a trabalhar neles.',
    '6':'Invista no seu próprio bem-estar. Reservar um tempo para relaxar e descontrair melhorará seu humor, sua saúde mental e sua auto-estima. Todos os dias, faça pelo menos uma coisa que o deixe feliz.',
  },
};

Map<String, Map> moodDetails={
  'Hindi':{
    'Happy':'नमस्ते, यह सुनकर अच्छा लगा कि आप खुश महसूस कर रहे हैं। आपको इस बात का एहसास होना चाहिए कि खुशियों की कुंजी है खुद और अपने लिए खुश रहना..मुस्कुराते रहो।',
    'Angry':"नमस्ते, मुझे खेद है कि आप गुस्से में महसूस कर रहे हैं, लेकिन चिंता न करें, मैं यहां आपकी तरफ से हूं, कठिन समय और अच्छे समय में आपका समर्थन करने के लिए। क्रोध से कुछ हल नहीं होता। यह कुछ भी नहीं बनाता है, लेकिन यह सब कुछ नष्ट कर सकता है।",
    'Stress':"नमस्ते, मुझे खेद है कि आप तनावग्रस्त महसूस कर रहे हैं, लेकिन चिंता न करें मैं यहां आपकी तरफ से हूं, कठिन समय और अच्छे समय में आपका समर्थन करने के लिए। बड़े तनाव या विपत्ति के समय में, व्यस्त रहना, अपने क्रोध और अपनी ऊर्जा को किसी सकारात्मक चीज़ में लगाना हमेशा सर्वोत्तम होता है।",
    'Lonely':"नमस्ते, मुझे खेद है कि आप अकेलापन महसूस कर रहे हैं, लेकिन चिंता न करें कि मैं यहां आपकी तरफ से हूं, कठिन समय और अच्छे समय में आपका समर्थन करने के लिए। महसूस करें कि आप अकेले नहीं हैं, हम इसमें एक साथ हैं और सबसे महत्वपूर्ण बात यह है कि आशा है।",
    'Depressed':"नमस्ते, आप मजबूत पाए जाते हैं, क्योंकि आप नशे से लड़ते हुए पाए गए थे। यह एक काला दौर है, जिसे आप अपने दिल के अंदर अंगारे की मदद से दूर कर लेंगे। अब अपने पंखों के साथ ऊंची उड़ान भरने का समय आ गया है।",
    'Tired':"नमस्ते, मुझे खेद है कि आप थका हुआ महसूस कर रहे हैं, लेकिन चिंता न करें मैं यहां आपकी तरफ से हूं। हर बार जब आप थका हुआ महसूस करते हैं, तो खुद को याद दिलाएं कि आप जो कर रहे हैं वह क्यों कर रहे हैं और चलते रहें।",
    'Anxiety':"नमस्ते, मुझे खेद है कि आप चिंता महसूस कर रहे हैं, लेकिन चिंता न करें मैं यहां आपकी तरफ से हूं। चिंता तब होती है जब आपको लगता है कि आपको एक ही बार में सब कुछ पता लगाना है। एक सांस लें... आप मजबूत हैं। आपको यह मिला। इसे दिन-प्रतिदिन लें।",
    'Sad':"नमस्ते, मुझे खेद है कि आप उदास महसूस कर रहे हैं, लेकिन चिंता न करें मैं यहां आपकी तरफ से हूं, कठिन समय और अच्छे समय में आपका समर्थन करने के लिए।",
  },
  'English':{
    'Happy':'Hey, Good to hear that you are feeling Happy. The thing you should realize is that the key to happiness is being happy by yourself and for yourself.. keep smiling.',
    'Angry':"Hey, I’m sorry that you are feeling Angry but don’t worry I'm here to be by your side, to support you through the hard times and the good.  Anger doesn’t solve anything. It builds nothing, but it can destroy everything.",
    'Stress':"Hey, I’m sorry that you are feeling Stressed but don’t worry I'm here to be by your side, to support you through the hard times and the good.  In times of great stress or adversity, it's always best to keep busy, to plow your anger and your energy into something positive.",
    'Depressed':"Hey, You are detected strong, as you were found fighting addiction. It's a dark phase, which you will overcome with the help of ember inside your heart. Now it's time to fly high with your wings.",
    'Fear':"Hey, I’m sorry that you are feeling Fear but don’t worry I'm here to be by your side.  Be Brave, The thing about being brave is it doesn't come with the absence of fear and hurt. Bravery is the ability to look fear and hurt in the face and say move aside, you are in the way.",
    'Tired':"Hey, I’m sorry that you are feeling Tired but don’t worry I'm here to be by your side.  Every time you feel tired, remind yourself of why you are doing what you are doing and keep going.",
    'Anxiety':"Hey, I’m sorry that you are feeling Anxiety but don’t worry I'm here to be by your side. Anxiety happens when you think you have to figure out everything all at once. Take a Breathe… You're strong. You got this. Take it day by day.",
    'Sad':"Hey, I’m sorry that you are feeling Sad but don’t worry I'm here to be by your side, to support you through the hard times and the good",
  },
  'Spanish':{
    'Happy':'Hola, Es bueno saber que te sientes feliz. Lo que debes darte cuenta es que la clave de la felicidad es ser feliz por ti mismo y por ti mismo ... sigue sonriendo',
    'Angry':"Hola, Lamento que te sientas enojado, pero no te preocupes, estoy aquí para estar a tu lado, para apoyarte en los momentos difíciles y buenos. La ira no resuelve nada. No construye nada, pero puede destruirlo todo.",
    'Stress':"Hola, Lamento que se sienta estresado, pero no se preocupe, estoy aquí para estar a su lado, para apoyarlo en los momentos difíciles y buenos. En momentos de gran estrés o adversidad, siempre es mejor mantenerse ocupado, invertir su ira y su energía en algo positivo.",
    'Lonely':"Hola, Lamento que te sientas solo, pero no te preocupes, estoy aquí para estar a tu lado, para apoyarte en los momentos difíciles y buenos. Date cuenta de que no estás solo, estamos juntos en esto y lo más importante es que hay esperanza.",
    'Depressed':"Hola, Se le detecta fuerte, ya que se le encontró luchando contra la adicción. Es una fase oscura, que superarás con la ayuda de la brasa dentro de tu corazón. Ahora es el momento de volar alto con tus alas.",
    'Tired':"Hola, Lamento que se sienta cansado, pero no se preocupe, estoy aquí para estar a su lado. Cada vez que se sienta cansado, recuerde por qué está haciendo lo que está haciendo y continúe.",
    'Anxiety':"Hola, Lamento que estés sintiendo ansiedad, pero no te preocupes, estoy aquí para estar a tu lado. La ansiedad ocurre cuando crees que tienes que resolver todo de una vez. Toma un respiro… Eres fuerte. Lo tienes. Tómalo día a día.",
    'Sad':"Hola, Lamento que se sienta triste, pero no se preocupe, estoy aquí para estar a su lado, para apoyarlo en los momentos difíciles y buenos.",
  },
  'German':{
    'Happy':'Hey, schön zu hören, dass du dich glücklich fühlst. Du solltest erkennen, dass der Schlüssel zum Glück darin besteht, allein und für sich selbst glücklich zu sein. Lächle weiter.',
    'Angry':"Hey, Es tut mir leid, dass Sie wütend sind, aber keine Sorge, ich bin hier, um an Ihrer Seite zu sein, um Sie durch die schweren und guten Zeiten zu unterstützen. Wut löst nichts. Es baut nichts, aber es kann alles zerstören.",
    'Stress':"Hey, Es tut mir leid, dass Sie sich gestresst fühlen, aber keine Sorge, ich bin hier, um an Ihrer Seite zu sein, um Sie in den schweren und guten Zeiten zu unterstützen. In Zeiten von großem Stress oder Widrigkeiten ist es immer am besten, beschäftigt zu sein, Ihre Wut und Ihre Energie in etwas Positives zu stecken.",
    'Lonely':"Hey, Es tut mir leid, dass du dich einsam fühlst, aber keine Sorge, ich bin hier, um an deiner Seite zu sein, um dich durch die schweren und guten Zeiten zu unterstützen. Erkenne, dass du nicht allein bist, wir sind zusammen dabei und vor allem, dass es Hoffnung gibt.",
    'Depressed':"Hey, Sie werden stark erkannt, da Sie im Kampf gegen die Sucht gefunden wurden. Es ist eine dunkle Phase, die du mit Hilfe der Glut in deinem Herzen überwinden wirst. Jetzt ist es an der Zeit, mit deinen Flügeln hoch zu fliegen.",
    'Tired':"Hey, Es tut mir leid, dass Sie sich müde fühlen, aber keine Sorge, ich bin hier, um an Ihrer Seite zu sein. Jedes Mal, wenn Sie sich müde fühlen, erinnern Sie sich daran, warum Sie das tun, was Sie tun, und machen Sie weiter.",
    'Anxiety':"Hey, Es tut mir leid, dass Sie Angst haben, aber keine Sorge, ich bin hier, um an Ihrer Seite zu sein. Angst entsteht, wenn du denkst, du musst alles auf einmal herausfinden. Atmen Sie durch... Sie sind stark. Du schaffst das. Nimm es Tag für Tag.",
    'Sad':"Hey, Es tut mir leid, dass Sie sich traurig fühlen, aber keine Sorge, ich bin hier, um an Ihrer Seite zu sein, um Sie durch die schweren und guten Zeiten zu unterstützen.",
  },
  'French':{
    'Happy':"Hey, Content d'entendre que tu te sens heureux. La chose que vous devez comprendre, c'est que la clé du bonheur est d'être heureux par vous-même et pour vous-même. gardez le sourire",
    'Angry':"Hey, Je suis désolé que vous vous sentiez en colère, mais ne vous inquiétez pas, je suis là pour être à vos côtés, pour vous soutenir dans les moments difficiles et les bons. La colère ne résout rien. Il ne construit rien, mais il peut tout détruire.",
    'Stress':"Hey, Je suis désolé que vous vous sentiez stressé, mais ne vous inquiétez pas, je suis là pour être à vos côtés, pour vous soutenir dans les moments difficiles et les bons. En période de grand stress ou d'adversité, il est toujours préférable de rester occupé, de consacrer votre colère et votre énergie à quelque chose de positif.",
    'Lonely':"Hey, Je suis désolé que vous vous sentiez seul, mais ne vous inquiétez pas, je suis là pour être à vos côtés, pour vous soutenir dans les moments difficiles et les bons. Réalisez que vous n'êtes pas seul, nous sommes dans le même bateau et surtout qu'il y a de l'espoir.",
    'Depressed':"Hey, Vous êtes détecté fort, car vous avez été trouvé en train de lutter contre la dépendance. C'est une phase sombre, que vous surmonterez avec l'aide de la braise à l'intérieur de votre cœur. Il est maintenant temps de voler haut avec vos ailes.",
    'Tired':"Hey, Je suis désolé que vous vous sentiez fatigué, mais ne vous inquiétez pas, je suis là pour être à vos côtés. Chaque fois que vous vous sentez fatigué, rappelez-vous pourquoi vous faites ce que vous faites et continuez.",
    'Anxiety':"Hey, Je suis désolé que vous ressentiez de l'anxiété, mais ne vous inquiétez pas, je suis là pour être à vos côtés. L'anxiété survient lorsque vous pensez que vous devez tout comprendre d'un seul coup. Respirez… Vous êtes fort. Tu as ça. Prenez-le au jour le jour.",
    'Sad':"Hey, Je suis désolé que vous vous sentiez triste mais ne vous inquiétez pas, je suis là pour être à vos côtés, pour vous soutenir dans les moments difficiles et les bons.",
  },
  'Japanese':{
    'Happy':'ねえ、あなたが幸せを感じていると聞いてうれしいです。あなたが気づかなければならないことは、幸せへの鍵はあなた自身とあなた自身のために幸せであるということです..笑顔を保ちます',
    'Angry':"ねえ、あなたが怒りを感じていることをお詫びしますが、私があなたのそばにいて、困難な時と良い時を通してあなたをサポートするためにここにいることを心配しないでください。怒りは何も解決しません。それは何も構築しませんが、すべてを破壊する可能性があります。",
    'Stress':"ねえ、あなたがストレスを感じていることをお詫びしますが、私があなたのそばにいて、困難な時と良い時を通してあなたをサポートするためにここにいることを心配しないでください。大きなストレスや逆境の時には、忙しくして、怒りとエネルギーを何か前向きなものに変えることが常に最善です。",
    'Lonely':"ねえ、あなたが孤独を感じていることをお詫びしますが、私があなたのそばにいて、困難な時と良い時を通してあなたをサポートするためにここにいることを心配しないでください。あなたが一人ではないことを認識してください。私たちは一緒にこれに参加しており、最も重要なのは希望があることです。",
    'Depressed':"ねえ、あなたは中毒と戦っているのが発見されたので、あなたは強いと検出されます。それはあなたがあなたの心の中の残り火の助けを借りて克服するであろう暗い段階です。さあ、翼を持って高く飛ぶ時が来ました。",
    'Tired':"ねえ、疲れを感じて申し訳ありませんが、私があなたのそばにいることを心配しないでください。疲れを感じるたびに、自分がしていることをしている理由を思い出し、続けてください。",
    'Anxiety':"ねえ、あなたが不安を感じていることをお詫びしますが、私があなたのそばにいることを心配しないでください。あなたが一度にすべてを理解しなければならないと思うとき、不安は起こります。息をしてください…あなたは強いです。あなたはこれを得ました。毎日それを取りなさい。",
    'Sad':"ねえ、あなたが悲しんでいることを残念に思いますが、私があなたのそばにいて、困難な時と良い時を通してあなたをサポートするためにここにいることを心配しないでください。",
  },
  'Russian':{
    'Happy':'Привет, Приятно слышать, что вы счастливы. Вы должны понимать, что ключ к счастью - это быть счастливым в одиночестве и для себя ... продолжайте улыбаться',
    'Angry':"Привет, Мне жаль, что ты злишься, но не волнуйся, я здесь, чтобы быть рядом с тобой, чтобы поддержать тебя в трудные и хорошие времена. Гнев ничего не решает. Он ничего не строит, но может все разрушить.",
    'Stress':"Привет, Мне жаль, что вы испытываете стресс, но не волнуйтесь, я здесь, чтобы быть рядом с вами, чтобы поддержать вас в трудные и хорошие времена. Во время сильного стресса или невзгод всегда лучше оставаться чем-то занятым, направить свой гнев и свою энергию на что-то позитивное.",
    'Lonely':"Привет, Мне жаль, что ты чувствуешь себя Одиноким, но не волнуйся, я здесь, чтобы быть рядом с тобой, чтобы поддержать тебя в трудные и хорошие времена. Поймите, что вы не одиноки, мы в этом вместе и, самое главное, есть надежда.",
    'Depressed':"Привет, Вас считают сильным, поскольку вы боретесь с зависимостью. Это темная фаза, которую вы преодолеете с помощью тлеющего угля в своем сердце. Пришло время взлететь высоко на крыльях.",
    'Tired':"Привет, Мне жаль, что вы устали, но не волнуйтесь, я здесь, чтобы быть рядом с вами. Каждый раз, когда вы чувствуете усталость, напоминайте себе, почему вы делаете то, что делаете, и продолжайте.",
    'Anxiety':"Привет, Мне жаль, что вы чувствуете беспокойство, но не волнуйтесь, я здесь, чтобы быть рядом с вами. Тревога возникает, когда вы думаете, что вам нужно во всем разобраться. Сделай вдох… Ты сильный. Ты получил это. Принимайте это изо дня в день.",
    'Sad':"Привет, Мне жаль, что тебе грустно, но не волнуйся, я здесь, чтобы быть рядом с тобой, чтобы поддержать тебя в трудные и хорошие времена.",
  },
  'Chinese':{
    'Happy':'嘿, 很高兴听到你感到快乐。你应该意识到，幸福的关键是让自己和自己快乐。保持微笑，在你身边，支持你度过艰难时期和美好时光。',
    'Angry':"嘿, 我很抱歉让您感到愤怒，但请放心，我会在您身边，支持您度过艰难时期和美好时光。愤怒解决不了任何问题。它什么也不建，但它可以摧毁一切。",
    'Stress':"嘿, 很抱歉您感到压力很大，但请放心，我会在您身边，支持您度过艰难时期和美好时光。在压力大或逆境的时候，最好保持忙碌，把你的愤怒和能量转化为积极的东西。",
    'Lonely':"嘿, 我很抱歉你感到孤独，但别担心，我会在你身边，支持你度过艰难时期和美好时光。意识到您并不孤单，我们在一起，最重要的是还有希望。",
    'Depressed':"嘿, 你被发现很强壮，因为你被发现与毒瘾作斗争。这是一个黑暗的阶段，你将在你心中的余烬的帮助下克服它。现在是时候用你的翅膀飞得很高了。",
    'Tired':"嘿, 很抱歉让您感到疲倦，但请放心，我会在您身边。每次感到疲倦时，请提醒自己为什么要做正在做的事情并继续前进。",
    'Anxiety':"嘿, 很抱歉您感到焦虑，但请放心，我会在您身边。当您认为必须一下子弄清楚所有事情时，就会感到焦虑。深呼吸……你很强壮。你得到了这个。日复一日地服用。",
    'Sad':"嘿, 我很抱歉让你感到悲伤，但别担心，我会在你身边，支持你度过艰难时期和美好时光。",
  },
  'Portuguese':{
    'Happy':'Olá, É bom saber que você está se sentindo feliz. O que você deve entender é que a chave para a felicidade é ser feliz por você e por si mesmo .. continue sorrindo',
    'Angry':"Olá, Lamento que você esteja com raiva, mas não se preocupe. Estou aqui para estar ao seu lado, para apoiá-lo nos momentos difíceis e bons. A raiva não resolve nada. Não constrói nada, mas pode destruir tudo.",
    'Stress':"Olá, Lamento que você esteja se sentindo estressado, mas não se preocupe. Estou aqui para estar ao seu lado, para apoiá-lo nos momentos difíceis e bons. Em tempos de grande estresse ou adversidade, é sempre melhor manter-se ocupado, transformar sua raiva e energia em algo positivo.",
    'Lonely':"Olá, Lamento que você esteja se sentindo Solitário, mas não se preocupe. Estou aqui para estar ao seu lado, para apoiá-lo nos momentos difíceis e bons Perceba que você não está sozinho, estamos juntos nisso e o mais importante é que há esperança.",
    'Depressed':"Olá, Você foi detectado como forte, pois foi encontrado lutando contra o vício. É uma fase sombria, que você superará com a ajuda da brasa dentro do seu coração. Agora é hora de voar alto com suas asas.",
    'Tired':"Olá, Lamento que você esteja se sentindo cansado, mas não se preocupe, estou aqui para estar ao seu lado. Sempre que se sentir cansado, lembre-se do motivo pelo qual está fazendo o que está fazendo e continue.",
    'Anxiety':"Ei, Lamento que você esteja sentindo ansiedade, mas não se preocupe, estou aqui para estar ao seu lado. A ansiedade acontece quando você pensa que tem que descobrir tudo de uma vez. Respire ... Você é forte. Você conseguiu. Leve-o dia após dia.",
    'Sad':"Olá, Lamento que você esteja triste, mas não se preocupe. Estou aqui para estar ao seu lado, para apoiá-lo nos momentos difíceis e bons.",
  },
};

var decisionDetails={
  'Hindi':{
    'beginner':"चिंता न करें, आप केवल व्यसन के शुरुआती चरण में हैं। मैं समझता हूं कि आप कैसा महसूस करते हैं, लेकिन इससे छुटकारा पाना कठिन नहीं है। आप अकेले नहीं हैं; व्यसन एक ऐसी समस्या है जिसका सामना आजकल बहुत से लोग करते हैं। लेकिन आप चिंता न करें, मैं आपकी सहायता के लिए यहां हूं।",
    'advanced':"आपकी स्थिति के बारे में सुनकर मुझे खेद है। लेकिन चिंता न करें मैं आपकी मदद करने के लिए यहां हूं। आप कभी-कभी अपनी भावनाओं को प्रबंधित करने के लिए संघर्ष कर सकते हैं और ऐसे काम करना शुरू कर सकते हैं जो आपको बुरी तरह प्रभावित कर सकते हैं। आप चाहे कितनी भी बुरी तरह से चाहें, बिना कुछ किए सब कुछ ठीक कर लें। चिंता न करें अपनी जीवनशैली बदलने के लिए समय निश्चित नहीं है। चलो मेरे साथ अपने जीवन का एक नया अध्याय शुरू करते हैं।",
    'intermediate':"मुझे खुशी है कि आपने पहले महसूस किया है कि आप अपने जीवन के बुरे रास्ते पर हैं। लेकिन चिंता न करें हम इसे जल्द ही दूर कर लेंगे क्योंकि जैसा कि मैंने कहा कि आपके जीवन में कुछ सकारात्मक जोड़ने का कोई निश्चित समय नहीं है।",
  },
  'English':{
    'beginner':"Don't worry, you're only at the outset stage of addiction. I understand how you feel, but getting rid of it is not tough. You're not alone; addiction is a problem that many people face nowadays. But don't you worry, I am here to assist you.",
    'advanced':"I’m sorry to hear about your situation. But Don’t worry I am here to help you. You may sometimes struggle to manage your emotions and start doing those things which can affect you badly. No matter how badly you want to,  fix everything without doing it. Don’t worry time is not fixed to change your lifestyle. Let’s start a new chapter of your life with me.",
    'intermediate':"I am happy that you have realized earlier that you are on the bad path of your life. But don’t worry we will overcome it shortly because as I said there is no fixed time to add something positive to your life.",
  },
  'Spanish':{
    'beginner':"No se preocupe, solo se encuentra en la etapa inicial de la adicción. Entiendo cómo se siente, pero deshacerse de él no es difícil. No estás solo; La adicción es un problema al que se enfrentan muchas personas en la actualidad. Pero no te preocupes, estoy aquí para ayudarte.",
    'advanced':"Lamento escuchar tu situación. Pero no se preocupe, estoy aquí para ayudarlo. A veces, puede tener dificultades para manejar sus emociones y comenzar a hacer aquellas cosas que pueden afectarlo gravemente. No importa cuánto lo desee, arregle todo sin hacerlo. No se preocupe, el tiempo no está fijo para cambiar su estilo de vida. Comencemos un nuevo capítulo de tu vida conmigo.",
    'intermediate':"Me alegra que te hayas dado cuenta antes de que estás en el mal camino de tu vida. Pero no te preocupes, lo superaremos en breve porque, como dije, no hay un tiempo fijo para agregar algo positivo a tu vida.",
  },
  'German':{
    'beginner':"Keine Sorge, Sie sind erst am Anfang der Sucht. Ich verstehe, wie du dich fühlst, aber es ist nicht schwer, es loszuwerden. Du bist nicht allein; Sucht ist ein Problem, mit dem viele Menschen heutzutage konfrontiert sind. Aber keine Sorge, ich bin hier, um Ihnen zu helfen.",
    'advanced':"Es tut mir leid, von Ihrer Situation zu hören. Aber keine Sorge, ich bin hier, um Ihnen zu helfen. Sie können manchmal Schwierigkeiten haben, mit Ihren Emotionen umzugehen und Dinge zu tun, die Sie schlecht beeinflussen können. Egal wie sehr Sie es wollen, reparieren Sie alles, ohne es zu tun. Keine Sorge, die Zeit ist nicht festgelegt, um Ihren Lebensstil zu ändern. Lass uns mit mir einen neuen Lebensabschnitt beginnen.",
    'intermediate':"Ich freue mich, dass Sie früher erkannt haben, dass Sie auf dem schlechten Weg Ihres Lebens sind. Aber keine Sorge, wir werden es in Kürze überwinden, denn wie gesagt, es gibt keine feste Zeit, um Ihrem Leben etwas Positives hinzuzufügen.",
  },
  'French':{
    'beginner':"Ne vous inquiétez pas, vous n'êtes qu'au stade initial de la dépendance. Je comprends ce que tu ressens, mais s'en débarrasser n'est pas difficile. Tu n'es pas seul; La toxicomanie est un problème auquel de nombreuses personnes sont confrontées de nos jours. Mais ne vous inquiétez pas, je suis là pour vous aider.",
    'advanced':"Je suis désolé d'apprendre votre situation. Mais ne vous inquiétez pas, je suis là pour vous aider. Vous pouvez parfois avoir du mal à gérer vos émotions et commencer à faire des choses qui peuvent vous affecter gravement. Peu importe à quel point vous le souhaitez, réparez tout sans le faire. Ne vous inquiétez pas, le temps n'est pas fixé pour changer votre style de vie. Commençons avec moi un nouveau chapitre de ta vie.",
    'intermediate':"Je suis heureux que vous ayez réalisé plus tôt que vous êtes sur le mauvais chemin de votre vie. Mais ne vous inquiétez pas, nous allons le surmonter sous peu car, comme je l'ai dit, il n'y a pas de temps fixe pour ajouter quelque chose de positif à votre vie.",
  },
  'Japanese':{
    'beginner':"心配しないでください、あなたは中毒の最初の段階にすぎません。私はあなたがどのように感じているかを理解していますが、それを取り除くことは難しいことではありません。あなたは一人じゃない;中毒は、今日多くの人々が直面している問題です。しかし、心配しないでください、私はあなたを助けるためにここにいます。",
    'advanced':"ご不便をおかけして申し訳ございません。しかし、私があなたを助けるためにここにいることを心配しないでください。あなたは時々あなたの感情を管理するのに苦労し、あなたに悪い影響を与える可能性のあることを始めます。どんなにひどくやりたいとしても、それをせずにすべてを修正してください。あなたのライフスタイルを変えるために時間が固定されていないことを心配しないでください。私と一緒にあなたの人生の新しい章を始めましょう。",
    'intermediate':"あなたが自分の人生の悪い道を進んでいることに早く気づいたことを嬉しく思います。しかし、私が言ったように、あなたの人生に何か前向きなものを加えるための決まった時間はないので、私たちがすぐにそれを克服することを心配しないでください。",
  },
  'Russian':{
    'beginner':"Не волнуйтесь, у вас только начальная стадия зависимости. Я понимаю, как вы себя чувствуете, но избавиться от этого несложно. Ты не одинок; зависимость - проблема, с которой сегодня сталкиваются многие люди. Но не волнуйтесь, я здесь, чтобы помочь вам.",
    'advanced':"Мне жаль слышать о вашей ситуации. Но не волнуйтесь, я здесь, чтобы помочь вам. Иногда вам может быть трудно справиться со своими эмоциями и начать делать то, что может плохо на вас повлиять. Как бы сильно вы ни хотели, исправляйте все, не делая этого. Не волнуйтесь, время не ограничено, чтобы изменить ваш образ жизни. Давайте вместе со мной начнем новую главу вашей жизни.",
    'intermediate':"Я счастлив, что вы раньше осознали, что идете по плохому жизненному пути. Но не волнуйтесь, мы скоро преодолеем это, потому что, как я уже сказал, нет определенного времени, чтобы добавить что-то позитивное в вашу жизнь.",
  },
  'Chinese':{
    'beginner':"别担心，你只是在上瘾的开始阶段。我理解你的感受，但摆脱它并不难。你不是一个人;成瘾是当今许多人面临的问题。但是你不用担心，我是来帮助你的。",
    'advanced':"我很遗憾听到你的情况。但别担心，我是来帮助你的。有时您可能难以控制自己的情绪，并开始做那些可能对您造成严重影响的事情。无论您多么想修复一切，都不做。别担心，改变生活方式的时间不是固定的。和我一起开启你人生的新篇章。",
    'intermediate':"我很高兴你早点意识到你正走在人生的糟糕道路上。但别担心，我们很快就会克服它，因为正如我所说，没有固定的时间来为你的生活添加一些积极的东西。",
  },
  'Portuguese':{
    'beginner':"Não se preocupe, você está apenas no estágio inicial do vício. Eu entendo como você se sente, mas se livrar disso não é difícil. Você não está sozinho; o vício é um problema que muitas pessoas enfrentam hoje em dia. Mas não se preocupe, estou aqui para ajudá-lo.",
    'advanced':"Lamento saber sobre sua situação. Mas não se preocupe, estou aqui para ajudá-lo. Você pode às vezes lutar para controlar suas emoções e começar a fazer coisas que podem afetá-lo gravemente. Não importa o quanto você queira, conserte tudo sem fazer isso. Não se preocupe, o tempo não está determinado para mudar seu estilo de vida. Vamos começar um novo capítulo de sua vida comigo.",
    'intermediate':"Estou feliz por você ter percebido antes que está no caminho ruim da sua vida. Mas não se preocupe, vamos superar isso em breve porque, como eu disse, não há tempo fixo para adicionar algo positivo à sua vida.",
  },
};